$('.owl-carousel').owlCarousel({
    margin:10,
    loop:true,
    autoWidth:true,
    items:4
})
$(document).ready(function(){
    $(".period-toggle").click(function(){
        $(".year").toggleClass("actives");
        $(".month").toggleClass("activesl");
        $(".content").toggleClass("lefts");
    });
    $(".fa-bars").click(function(){
        $(".mobile_menu").toggleClass("come")
    })
    $(".fa-xmark").click(function(){
        $(".mobile_menu").removeClass("come")
    })
 
  });
  AOS.init();